apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP-Z-d
  namespace: APP-Z
  labels:
    app: APP-Z
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP-Z
  template:
    metadata:
      labels:
        app: APP-Z
    spec:
      containers:
      - image: amitmohleji/appz:{{BUILD_NUMBER}}
        name: APP-Z
---
apiVersion: v1
kind: Service
metadata:
  name: APP-Z
  namespace: APP-Z
spec:
  selector: 
    app: APP-Z
  type: ClusterIP
  ports:
      - port: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: APP-Z
  namespace: APP-Z
spec:
  to:
    kind: Service
    name: APP-Z
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
status:
  ingress:
    - routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None

